/**
 * Definições de achievements
 * @module lib/gamification/achievement-definitions
 */

import type { Achievement } from './gamification-types';

export const ACHIEVEMENTS: Achievement[] = [
  // KPI Achievements
  {
    id: 'first-kpi',
    name: 'Primeiro Passo',
    description: 'Crie seu primeiro KPI',
    category: 'kpi',
    rarity: 'common',
    icon: '📊',
    xpReward: 50,
    condition: { type: 'count', metric: 'kpis_created', target: 1 },
    isProgressive: false,
    isSecret: false,
    order: 1,
  },
  {
    id: 'kpi-creator-10',
    name: 'Criador de Métricas',
    description: 'Crie 10 KPIs',
    category: 'kpi',
    rarity: 'uncommon',
    icon: '📈',
    xpReward: 150,
    condition: { type: 'count', metric: 'kpis_created', target: 10 },
    isProgressive: true,
    maxProgress: 10,
    isSecret: false,
    order: 2,
  },
  {
    id: 'kpi-master',
    name: 'Mestre dos KPIs',
    description: 'Crie 50 KPIs',
    category: 'kpi',
    rarity: 'epic',
    icon: '🎯',
    xpReward: 500,
    condition: { type: 'count', metric: 'kpis_created', target: 50 },
    isProgressive: true,
    maxProgress: 50,
    isSecret: false,
    order: 3,
  },
  {
    id: 'target-achieved',
    name: 'Na Mosca!',
    description: 'Atinja 100% da meta em um KPI',
    category: 'kpi',
    rarity: 'uncommon',
    icon: '🎯',
    xpReward: 200,
    condition: { type: 'threshold', metric: 'kpi_target_achieved', target: 1 },
    isProgressive: false,
    isSecret: false,
    order: 4,
  },
  {
    id: 'target-master',
    name: 'Meta Mestre',
    description: 'Atinja 100% da meta em 5 KPIs diferentes',
    category: 'kpi',
    rarity: 'rare',
    icon: '🏆',
    xpReward: 500,
    condition: { type: 'count', metric: 'kpis_at_100_percent', target: 5 },
    isProgressive: true,
    maxProgress: 5,
    isSecret: false,
    order: 5,
  },

  // Action Plan Achievements
  {
    id: 'first-plan',
    name: 'Planejador',
    description: 'Crie seu primeiro plano de ação',
    category: 'action_plan',
    rarity: 'common',
    icon: '📋',
    xpReward: 50,
    condition: { type: 'count', metric: 'plans_created', target: 1 },
    isProgressive: false,
    isSecret: false,
    order: 10,
  },
  {
    id: 'plan-completed',
    name: 'Missão Cumprida',
    description: 'Conclua um plano de ação',
    category: 'action_plan',
    rarity: 'uncommon',
    icon: '✅',
    xpReward: 200,
    condition: { type: 'count', metric: 'plans_completed', target: 1 },
    isProgressive: false,
    isSecret: false,
    order: 11,
  },
  {
    id: 'speed-runner',
    name: 'Speed Runner',
    description: 'Conclua um plano antes do prazo',
    category: 'action_plan',
    rarity: 'rare',
    icon: '⚡',
    xpReward: 300,
    condition: { type: 'count', metric: 'plans_completed_early', target: 1 },
    isProgressive: false,
    isSecret: false,
    order: 12,
  },
  {
    id: 'plan-master',
    name: 'Executor Mestre',
    description: 'Conclua 50 planos de ação',
    category: 'action_plan',
    rarity: 'epic',
    icon: '🌟',
    xpReward: 750,
    condition: { type: 'count', metric: 'plans_completed', target: 50 },
    isProgressive: true,
    maxProgress: 50,
    isSecret: false,
    order: 13,
  },

  // Streak Achievements
  {
    id: 'streak-3',
    name: 'Consistente',
    description: 'Use o sistema por 3 dias seguidos',
    category: 'streak',
    rarity: 'common',
    icon: '🔥',
    xpReward: 50,
    condition: { type: 'streak', metric: 'login_streak', target: 3 },
    isProgressive: false,
    isSecret: false,
    order: 20,
  },
  {
    id: 'streak-7',
    name: 'Dedicado',
    description: 'Use o sistema por 7 dias seguidos',
    category: 'streak',
    rarity: 'uncommon',
    icon: '🔥',
    xpReward: 150,
    condition: { type: 'streak', metric: 'login_streak', target: 7 },
    isProgressive: false,
    isSecret: false,
    order: 21,
  },
  {
    id: 'streak-30',
    name: 'Em Chamas!',
    description: 'Use o sistema por 30 dias seguidos',
    category: 'streak',
    rarity: 'rare',
    icon: '🔥',
    xpReward: 500,
    condition: { type: 'streak', metric: 'login_streak', target: 30 },
    isProgressive: true,
    maxProgress: 30,
    isSecret: false,
    order: 22,
  },
  {
    id: 'streak-100',
    name: 'Lendário',
    description: 'Use o sistema por 100 dias seguidos',
    category: 'streak',
    rarity: 'legendary',
    icon: '💎',
    xpReward: 2000,
    condition: { type: 'streak', metric: 'login_streak', target: 100 },
    isProgressive: true,
    maxProgress: 100,
    isSecret: false,
    order: 23,
  },

  // Collaboration Achievements
  {
    id: 'first-comment',
    name: 'Comunicador',
    description: 'Faça seu primeiro comentário',
    category: 'collaboration',
    rarity: 'common',
    icon: '💬',
    xpReward: 25,
    condition: { type: 'count', metric: 'comments_created', target: 1 },
    isProgressive: false,
    isSecret: false,
    order: 30,
  },
  {
    id: 'helpful',
    name: 'Prestativo',
    description: 'Receba 10 reações positivas',
    category: 'collaboration',
    rarity: 'uncommon',
    icon: '👍',
    xpReward: 200,
    condition: { type: 'count', metric: 'reactions_received', target: 10 },
    isProgressive: true,
    maxProgress: 10,
    isSecret: false,
    order: 31,
  },
  {
    id: 'team-player',
    name: 'Jogador de Equipe',
    description: 'Participe de 5 planos de ação diferentes',
    category: 'collaboration',
    rarity: 'rare',
    icon: '🤝',
    xpReward: 350,
    condition: { type: 'count', metric: 'plans_participated', target: 5 },
    isProgressive: true,
    maxProgress: 5,
    isSecret: false,
    order: 32,
  },

  // Secret Achievements
  {
    id: 'night-owl',
    name: 'Coruja Noturna',
    description: 'Atualize um KPI após meia-noite',
    category: 'engagement',
    rarity: 'rare',
    icon: '🦉',
    xpReward: 100,
    condition: { type: 'time_based', metric: 'kpi_updated_night', target: 1 },
    isProgressive: false,
    isSecret: true,
    order: 100,
  },
  {
    id: 'early-bird',
    name: 'Madrugador',
    description: 'Atualize um KPI antes das 6h',
    category: 'engagement',
    rarity: 'rare',
    icon: '🐦',
    xpReward: 100,
    condition: { type: 'time_based', metric: 'kpi_updated_early', target: 1 },
    isProgressive: false,
    isSecret: true,
    order: 101,
  },
  {
    id: 'perfectionist',
    name: 'Perfeccionista',
    description: 'Mantenha todos os KPIs acima de 90% por 30 dias',
    category: 'milestone',
    rarity: 'legendary',
    icon: '💯',
    xpReward: 2500,
    condition: { type: 'combination', metric: 'all_kpis_above_90_30_days', target: 1 },
    isProgressive: false,
    isSecret: true,
    order: 102,
  },
];

export function getAchievementById(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find((a) => a.id === id);
}

export function getAchievementsByCategory(category: Achievement['category']): Achievement[] {
  return ACHIEVEMENTS.filter((a) => a.category === category).sort((a, b) => a.order - b.order);
}

export function getVisibleAchievements(): Achievement[] {
  return ACHIEVEMENTS.filter((a) => !a.isSecret).sort((a, b) => a.order - b.order);
}
