/**
 * Registry de widgets disponíveis
 * @module lib/dashboard/widget-registry
 */

import type { WidgetDefinition, WidgetType } from './dashboard-types';

export const WIDGET_REGISTRY: Record<WidgetType, WidgetDefinition> = {
  kpi_card: {
    type: 'kpi_card',
    name: 'KPI Card',
    description: 'Exibe um KPI com valor atual e tendência',
    icon: '📊',
    category: 'kpi',
    defaultSize: { x: 0, y: 0, w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 6, h: 4 },
    defaultConfig: {
      type: 'kpi_card',
      showTrend: true,
      showVariation: true,
      showTarget: false,
      showStatus: true,
    },
  },
  kpi_chart: {
    type: 'kpi_chart',
    name: 'KPI Chart',
    description: 'Gráfico de evolução do KPI',
    icon: '📈',
    category: 'kpi',
    defaultSize: { x: 0, y: 0, w: 6, h: 3 },
    minSize: { w: 4, h: 2 },
    maxSize: { w: 12, h: 6 },
    defaultConfig: {
      type: 'kpi_chart',
      chartType: 'line',
      period: 'month',
      showTrend: true,
    },
  },
  kpi_gauge: {
    type: 'kpi_gauge',
    name: 'KPI Gauge',
    description: 'Velocímetro com progresso do KPI',
    icon: '⏱️',
    category: 'kpi',
    defaultSize: { x: 0, y: 0, w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 4 },
    defaultConfig: {
      type: 'kpi_gauge',
      showTarget: true,
      showStatus: true,
    },
  },
  kpi_table: {
    type: 'kpi_table',
    name: 'KPI Table',
    description: 'Tabela com múltiplos KPIs',
    icon: '📋',
    category: 'kpi',
    defaultSize: { x: 0, y: 0, w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 8 },
    defaultConfig: {
      type: 'kpi_table',
      showTrend: true,
      showVariation: true,
      showTarget: true,
      showStatus: true,
    },
  },
  goal_progress: {
    type: 'goal_progress',
    name: 'Goal Progress',
    description: 'Progresso geral das metas',
    icon: '🎯',
    category: 'goals',
    defaultSize: { x: 0, y: 0, w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 8, h: 6 },
    defaultConfig: {
      type: 'goal_progress',
      showPercentage: true,
      showValue: true,
    },
  },
  goal_bars: {
    type: 'goal_bars',
    name: 'Goal Bars',
    description: 'Barras de progresso por meta',
    icon: '📊',
    category: 'goals',
    defaultSize: { x: 0, y: 0, w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 8 },
    defaultConfig: {
      type: 'goal_bars',
      showPercentage: true,
      showValue: false,
    },
  },
  okr_tree: {
    type: 'okr_tree',
    name: 'OKR Tree',
    description: 'Árvore hierárquica de OKRs',
    icon: '🌳',
    category: 'goals',
    defaultSize: { x: 0, y: 0, w: 6, h: 5 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 8 },
    defaultConfig: {
      type: 'okr_tree',
      showKeyResults: true,
    },
  },
  okr_progress: {
    type: 'okr_progress',
    name: 'OKR Progress',
    description: 'Progresso de um OKR específico',
    icon: '🎯',
    category: 'goals',
    defaultSize: { x: 0, y: 0, w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 8, h: 5 },
    defaultConfig: {
      type: 'okr_progress',
      showKeyResults: true,
    },
  },
  action_plan_list: {
    type: 'action_plan_list',
    name: 'Action Plans',
    description: 'Lista de planos de ação',
    icon: '📋',
    category: 'plans',
    defaultSize: { x: 0, y: 0, w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 8, h: 8 },
    defaultConfig: {
      type: 'action_plan_list',
      limit: 5,
      showOverdue: true,
    },
  },
  action_plan_status: {
    type: 'action_plan_status',
    name: 'Plan Status',
    description: 'Distribuição de status dos planos',
    icon: '📊',
    category: 'plans',
    defaultSize: { x: 0, y: 0, w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 6, h: 4 },
    defaultConfig: {
      type: 'action_plan_status',
      showOverdue: true,
    },
  },
  pdca_cycle: {
    type: 'pdca_cycle',
    name: 'PDCA Cycle',
    description: 'Ciclo PDCA em andamento',
    icon: '🔄',
    category: 'plans',
    defaultSize: { x: 0, y: 0, w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 4 },
    defaultConfig: {
      type: 'pdca_cycle',
    },
  },
  alerts: {
    type: 'alerts',
    name: 'Alerts',
    description: 'Alertas e notificações recentes',
    icon: '🔔',
    category: 'other',
    defaultSize: { x: 0, y: 0, w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 6, h: 6 },
    defaultConfig: {
      type: 'alerts',
    },
  },
  leaderboard: {
    type: 'leaderboard',
    name: 'Leaderboard',
    description: 'Ranking de usuários',
    icon: '🏆',
    category: 'gamification',
    defaultSize: { x: 0, y: 0, w: 3, h: 4 },
    minSize: { w: 2, h: 3 },
    maxSize: { w: 6, h: 8 },
    defaultConfig: {
      type: 'leaderboard',
      period: 'month',
      limit: 5,
      showCurrentUser: true,
    },
  },
  streak: {
    type: 'streak',
    name: 'Streak',
    description: 'Seu streak atual',
    icon: '🔥',
    category: 'gamification',
    defaultSize: { x: 0, y: 0, w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    defaultConfig: {
      type: 'streak',
      showRecord: true,
      showCalendar: false,
    },
  },
  achievements: {
    type: 'achievements',
    name: 'Achievements',
    description: 'Conquistas recentes',
    icon: '🏅',
    category: 'gamification',
    defaultSize: { x: 0, y: 0, w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 8, h: 4 },
    defaultConfig: {
      type: 'achievements',
    },
  },
  activity_feed: {
    type: 'activity_feed',
    name: 'Activity Feed',
    description: 'Feed de atividades recentes',
    icon: '📰',
    category: 'other',
    defaultSize: { x: 0, y: 0, w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 6, h: 8 },
    defaultConfig: {
      type: 'activity_feed',
    },
  },
  text: {
    type: 'text',
    name: 'Text',
    description: 'Bloco de texto customizado',
    icon: '📝',
    category: 'other',
    defaultSize: { x: 0, y: 0, w: 4, h: 2 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 12, h: 4 },
    defaultConfig: {
      type: 'text',
      content: '',
      fontSize: 'medium',
      alignment: 'left',
    },
  },
  image: {
    type: 'image',
    name: 'Image',
    description: 'Imagem ou logo',
    icon: '🖼️',
    category: 'other',
    defaultSize: { x: 0, y: 0, w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 12, h: 8 },
    defaultConfig: {
      type: 'image',
    },
  },
};

export const WIDGET_CATEGORIES = {
  kpi: {
    name: 'KPIs',
    icon: '📊',
    widgets: ['kpi_card', 'kpi_chart', 'kpi_gauge', 'kpi_table'] as const,
  },
  goals: {
    name: 'Metas & OKRs',
    icon: '🎯',
    widgets: ['goal_progress', 'goal_bars', 'okr_tree', 'okr_progress'] as const,
  },
  plans: {
    name: 'Planos',
    icon: '📋',
    widgets: ['action_plan_list', 'action_plan_status', 'pdca_cycle'] as const,
  },
  gamification: {
    name: 'Gamificação',
    icon: '🏆',
    widgets: ['leaderboard', 'streak', 'achievements'] as const,
  },
  other: {
    name: 'Outros',
    icon: '📦',
    widgets: ['alerts', 'activity_feed', 'text', 'image'] as const,
  },
};
