/**
 * Templates padrão do sistema
 * @module lib/templates/default-templates
 */

import type { Template } from './template-types';

export const BSC_COMPLETE_TEMPLATE: Template = {
  id: 'system-bsc-complete',
  name: 'Balanced Scorecard Completo',
  description: 'Template completo com 16 KPIs nas 4 perspectivas do BSC',
  type: 'kpi',
  category: 'bsc',
  visibility: 'system',
  icon: '📊',
  color: '#8B5CF6',
  tags: ['bsc', 'estratégia', 'completo'],
  usageCount: 156,
  rating: 4.9,
  createdBy: 'system',
  createdByName: 'AuraCore',
  isSystem: true,
  isOwner: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  metadata: {
    version: '1.0',
    itemCount: 16,
    estimatedTime: '30 min',
    difficulty: 'intermediate',
  },
  variables: [
    {
      id: 'prefix',
      name: 'prefix',
      label: 'Prefixo para códigos',
      type: 'text',
      defaultValue: 'BSC',
      required: false,
      placeholder: 'Ex: BSC, KPI',
    },
    {
      id: 'startDate',
      name: 'startDate',
      label: 'Data inicial do período',
      type: 'date',
      required: true,
    },
  ],
  items: [
    // Financial Perspective
    {
      id: 'kpi-1',
      type: 'kpi',
      name: 'Margem Bruta',
      order: 1,
      properties: {
        code: '{{prefix}}-FIN-001',
        perspective: 'financial',
        unit: '%',
        frequency: 'monthly',
        targetValue: 35,
        formula: '(Receita - CMV) / Receita * 100',
      },
    },
    {
      id: 'kpi-2',
      type: 'kpi',
      name: 'EBITDA',
      order: 2,
      properties: {
        code: '{{prefix}}-FIN-002',
        perspective: 'financial',
        unit: 'R$',
        frequency: 'monthly',
      },
    },
    {
      id: 'kpi-3',
      type: 'kpi',
      name: 'Receita Líquida',
      order: 3,
      properties: {
        code: '{{prefix}}-FIN-003',
        perspective: 'financial',
        unit: 'R$',
        frequency: 'monthly',
      },
    },
    {
      id: 'kpi-4',
      type: 'kpi',
      name: 'ROI',
      order: 4,
      properties: {
        code: '{{prefix}}-FIN-004',
        perspective: 'financial',
        unit: '%',
        frequency: 'quarterly',
      },
    },
    // Customer Perspective
    {
      id: 'kpi-5',
      type: 'kpi',
      name: 'NPS',
      order: 5,
      properties: {
        code: '{{prefix}}-CLI-001',
        perspective: 'customer',
        unit: 'pts',
        frequency: 'monthly',
        targetValue: 50,
      },
    },
    {
      id: 'kpi-6',
      type: 'kpi',
      name: 'Satisfação do Cliente',
      order: 6,
      properties: {
        code: '{{prefix}}-CLI-002',
        perspective: 'customer',
        unit: '%',
        frequency: 'monthly',
        targetValue: 85,
      },
    },
    {
      id: 'kpi-7',
      type: 'kpi',
      name: 'Taxa de Retenção',
      order: 7,
      properties: {
        code: '{{prefix}}-CLI-003',
        perspective: 'customer',
        unit: '%',
        frequency: 'monthly',
        targetValue: 95,
      },
    },
    {
      id: 'kpi-8',
      type: 'kpi',
      name: 'OTD',
      order: 8,
      properties: {
        code: '{{prefix}}-CLI-004',
        perspective: 'customer',
        unit: '%',
        frequency: 'daily',
        targetValue: 95,
      },
    },
    // Internal Process
    {
      id: 'kpi-9',
      type: 'kpi',
      name: 'Produtividade',
      order: 9,
      properties: {
        code: '{{prefix}}-PRO-001',
        perspective: 'internal_process',
        unit: 'un/h',
        frequency: 'daily',
      },
    },
    {
      id: 'kpi-10',
      type: 'kpi',
      name: 'Taxa de Retrabalho',
      order: 10,
      properties: {
        code: '{{prefix}}-PRO-002',
        perspective: 'internal_process',
        unit: '%',
        frequency: 'weekly',
        targetValue: 2,
      },
    },
    {
      id: 'kpi-11',
      type: 'kpi',
      name: 'Lead Time',
      order: 11,
      properties: {
        code: '{{prefix}}-PRO-003',
        perspective: 'internal_process',
        unit: 'dias',
        frequency: 'weekly',
      },
    },
    {
      id: 'kpi-12',
      type: 'kpi',
      name: 'Utilização de Capacidade',
      order: 12,
      properties: {
        code: '{{prefix}}-PRO-004',
        perspective: 'internal_process',
        unit: '%',
        frequency: 'daily',
        targetValue: 85,
      },
    },
    // Learning & Growth
    {
      id: 'kpi-13',
      type: 'kpi',
      name: 'Horas de Treinamento',
      order: 13,
      properties: {
        code: '{{prefix}}-APR-001',
        perspective: 'learning_growth',
        unit: 'h',
        frequency: 'monthly',
        targetValue: 20,
      },
    },
    {
      id: 'kpi-14',
      type: 'kpi',
      name: 'Turnover',
      order: 14,
      properties: {
        code: '{{prefix}}-APR-002',
        perspective: 'learning_growth',
        unit: '%',
        frequency: 'monthly',
        targetValue: 5,
      },
    },
    {
      id: 'kpi-15',
      type: 'kpi',
      name: 'Índice de Engajamento',
      order: 15,
      properties: {
        code: '{{prefix}}-APR-003',
        perspective: 'learning_growth',
        unit: '%',
        frequency: 'quarterly',
        targetValue: 80,
      },
    },
    {
      id: 'kpi-16',
      type: 'kpi',
      name: 'Ideias Implementadas',
      order: 16,
      properties: {
        code: '{{prefix}}-APR-004',
        perspective: 'learning_growth',
        unit: 'un',
        frequency: 'monthly',
      },
    },
  ],
};

export const LOGISTICS_TEMPLATE: Template = {
  id: 'system-logistics',
  name: 'KPIs de Logística',
  description: 'Template com 8 KPIs essenciais para operações logísticas',
  type: 'kpi',
  category: 'logistics',
  visibility: 'system',
  icon: '🚚',
  color: '#10B981',
  tags: ['logística', 'transporte', 'armazém'],
  usageCount: 89,
  rating: 4.7,
  createdBy: 'system',
  createdByName: 'AuraCore',
  isSystem: true,
  isOwner: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  metadata: {
    version: '1.0',
    itemCount: 8,
    estimatedTime: '15 min',
    difficulty: 'beginner',
    industries: ['logística', 'transporte', 'e-commerce'],
  },
  variables: [
    {
      id: 'prefix',
      name: 'prefix',
      label: 'Prefixo para códigos',
      type: 'text',
      defaultValue: 'LOG',
      required: false,
    },
  ],
  items: [
    {
      id: 'log-1',
      type: 'kpi',
      name: 'OTD (On-Time Delivery)',
      order: 1,
      properties: {
        code: '{{prefix}}-001',
        perspective: 'customer',
        unit: '%',
        frequency: 'daily',
        targetValue: 95,
      },
    },
    {
      id: 'log-2',
      type: 'kpi',
      name: 'OTIF (On-Time In-Full)',
      order: 2,
      properties: {
        code: '{{prefix}}-002',
        perspective: 'customer',
        unit: '%',
        frequency: 'daily',
        targetValue: 92,
      },
    },
    {
      id: 'log-3',
      type: 'kpi',
      name: 'Custo por Entrega',
      order: 3,
      properties: {
        code: '{{prefix}}-003',
        perspective: 'financial',
        unit: 'R$',
        frequency: 'weekly',
      },
    },
    {
      id: 'log-4',
      type: 'kpi',
      name: 'Ocupação de Frota',
      order: 4,
      properties: {
        code: '{{prefix}}-004',
        perspective: 'internal_process',
        unit: '%',
        frequency: 'daily',
        targetValue: 85,
      },
    },
    {
      id: 'log-5',
      type: 'kpi',
      name: 'Acuracidade de Estoque',
      order: 5,
      properties: {
        code: '{{prefix}}-005',
        perspective: 'internal_process',
        unit: '%',
        frequency: 'weekly',
        targetValue: 99,
      },
    },
    {
      id: 'log-6',
      type: 'kpi',
      name: 'Pedidos por Hora',
      order: 6,
      properties: {
        code: '{{prefix}}-006',
        perspective: 'internal_process',
        unit: 'un/h',
        frequency: 'daily',
      },
    },
    {
      id: 'log-7',
      type: 'kpi',
      name: 'Taxa de Avarias',
      order: 7,
      properties: {
        code: '{{prefix}}-007',
        perspective: 'quality',
        unit: '%',
        frequency: 'weekly',
        targetValue: 0.5,
      },
    },
    {
      id: 'log-8',
      type: 'kpi',
      name: 'Devolução de Mercadorias',
      order: 8,
      properties: {
        code: '{{prefix}}-008',
        perspective: 'customer',
        unit: '%',
        frequency: 'weekly',
        targetValue: 2,
      },
    },
  ],
};

export const ACTION_PLAN_5W2H_TEMPLATE: Template = {
  id: 'system-5w2h',
  name: 'Plano de Ação 5W2H',
  description: 'Template de plano de ação com metodologia 5W2H',
  type: 'action_plan',
  category: 'quality',
  visibility: 'system',
  icon: '📋',
  color: '#F59E0B',
  tags: ['5w2h', 'ação', 'qualidade'],
  usageCount: 234,
  rating: 4.8,
  createdBy: 'system',
  createdByName: 'AuraCore',
  isSystem: true,
  isOwner: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  metadata: {
    version: '1.0',
    itemCount: 1,
    estimatedTime: '10 min',
    difficulty: 'beginner',
  },
  variables: [
    {
      id: 'title',
      name: 'title',
      label: 'Título do Plano',
      type: 'text',
      required: true,
      placeholder: 'Ex: Melhorar processo de expedição',
    },
    {
      id: 'what',
      name: 'what',
      label: 'O QUE será feito?',
      type: 'text',
      required: true,
    },
    {
      id: 'why',
      name: 'why',
      label: 'POR QUE será feito?',
      type: 'text',
      required: true,
    },
    {
      id: 'where',
      name: 'where',
      label: 'ONDE será feito?',
      type: 'text',
      required: false,
    },
    {
      id: 'when',
      name: 'when',
      label: 'QUANDO será feito?',
      type: 'date',
      required: true,
    },
  ],
  items: [],
  structure: {
    what: '{{what}}',
    why: '{{why}}',
    where: '{{where}}',
    how: [
      'Análise inicial',
      'Planejamento detalhado',
      'Execução',
      'Validação',
      'Documentação',
    ],
  },
  suggestedTasks: [
    { id: 't1', title: 'Análise inicial', order: 1, estimatedHours: 4 },
    { id: 't2', title: 'Planejamento detalhado', order: 2, estimatedHours: 8 },
    { id: 't3', title: 'Execução', order: 3, estimatedHours: 40 },
    { id: 't4', title: 'Validação', order: 4, estimatedHours: 4 },
    { id: 't5', title: 'Documentação', order: 5, estimatedHours: 2 },
  ],
};

export const PDCA_QUALITY_TEMPLATE: Template = {
  id: 'system-pdca-quality',
  name: 'Ciclo PDCA - Qualidade',
  description: 'Template de ciclo PDCA para projetos de melhoria de qualidade',
  type: 'pdca_cycle',
  category: 'quality',
  visibility: 'system',
  icon: '🔄',
  color: '#6366F1',
  tags: ['pdca', 'qualidade', 'melhoria contínua'],
  usageCount: 78,
  rating: 4.6,
  createdBy: 'system',
  createdByName: 'AuraCore',
  isSystem: true,
  isOwner: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  metadata: {
    version: '1.0',
    itemCount: 1,
    estimatedTime: '5 min',
    difficulty: 'intermediate',
  },
  variables: [
    {
      id: 'name',
      name: 'name',
      label: 'Nome do Ciclo',
      type: 'text',
      required: true,
    },
    {
      id: 'problem',
      name: 'problem',
      label: 'Problema a resolver',
      type: 'text',
      required: true,
    },
    {
      id: 'startDate',
      name: 'startDate',
      label: 'Data de início',
      type: 'date',
      required: true,
    },
  ],
  items: [
    {
      id: 'pdca-1',
      type: 'pdca_cycle',
      name: '{{name}}',
      description: '{{problem}}',
      order: 1,
      properties: {
        planDuration: 7,
        doDuration: 14,
        checkDuration: 7,
        actDuration: 7,
        checkpoints: [
          'Análise de causa raiz realizada',
          'Plano de ação definido',
          'Recursos alocados',
          'Métricas de sucesso definidas',
        ],
      },
    },
  ],
};

export const DEFAULT_TEMPLATES: Template[] = [
  BSC_COMPLETE_TEMPLATE,
  LOGISTICS_TEMPLATE,
  ACTION_PLAN_5W2H_TEMPLATE,
  PDCA_QUALITY_TEMPLATE,
];
